import os
from dotenv import load_dotenv
load_dotenv('.env')
import google.genai as genai
from pdf_processor import extract_text_from_pdf, chunk_text
from vector_store import FaissVectorStore
from chatbot import GeminiClient, QAEngine

API_KEY = os.environ.get('GEMINI_API_KEY')
genai_client = genai.Client(api_key=API_KEY) if API_KEY else None

print('Using genai SDK via client.models')

pdf_path = 'sample_resume.pdf'
with open(pdf_path, 'rb') as f:
    raw = f.read()

# 1) Extract
from io import BytesIO
print('\n--- PDF Extraction ---')
text = extract_text_from_pdf(BytesIO(raw))
print('Extracted text (truncated):')
print(text[:1000])

# 2) Chunk
print('\n--- Chunking ---')
chunks = chunk_text(text, chunk_size=500, overlap=100, max_chunks=50)
print('Chunks:', len(chunks))

# 3) Embed via SDK and show raw response
print('\n--- Embedding via SDK (raw response) ---')
# Prefer using our GeminiClient for embeddings so we can handle fallbacks and parsing
gem_client = GeminiClient(api_key=API_KEY)
try:
    emb_list = gem_client.embed_texts(chunks[:3])
    print('Embed returned count:', len(emb_list))
    if emb_list:
        print('First embedding length:', len(emb_list[0]))
    # create a minimal dict-like summary for compatibility
    d = {'embeddings': [{'values': e} for e in emb_list]}
except Exception as e:
    print('Embedding error:', e)
    raise

# 4) Vector store
print('\n--- Vector Store ---')
# determine embedding dim from SDK response
embs = [e.get('values') for e in d.get('embeddings', [])]
if not embs:
    raise RuntimeError('No embeddings returned')
emb_dim = len(embs[0])
print('Detected embedding dim:', emb_dim)
store = FaissVectorStore(embedding_dim=emb_dim)
store.add_documents(chunks[:len(embs)], embs)
print('Index size:', store.index.ntotal)

# 5) Chat with PDF
print('\n--- Chat with PDF ---')
engine = QAEngine(gemini_client=GeminiClient(api_key=API_KEY), store=store)
question = 'What are the candidate\'s key skills?'
print('Question:', question)
try:
    answer = engine.answer_question(question)
    print('Answer:', answer)
except Exception as e:
    print('Chat generation error:', e)

# 6) Generate Notes
print('\n--- Generate Notes ---')
try:
    # Use engine which calls GeminiClient.generate_text (has fallbacks)
    notes = engine.generate_notes()
    print('Notes generated (truncated):')
    print(str(notes)[:1000])
except Exception as e:
    print('Notes generation error:', e)

# 7) Generate Quiz
print('\n--- Generate Quiz ---')
try:
    quiz_prompt = engine.generate_mcqs()
    print('Quiz prompt (generated by engine):', quiz_prompt)
    # Use the engine's client to generate (handles fallbacks)
    import json
    if isinstance(quiz_prompt, (list, dict)):
        quiz_prompt_text = json.dumps(quiz_prompt)
    else:
        quiz_prompt_text = str(quiz_prompt)
    quiz_out = engine.client.generate_text(quiz_prompt_text, max_tokens=800)
    print('Quiz generation output (truncated):')
    print(str(quiz_out)[:1000])
except Exception as e:
    print('Quiz generation error:', e)

# 8) Key Concepts
print('\n--- Key Concepts (summarize) ---')
summary = engine.summarize()
print('Summary:', summary)

print('\nE2E run complete.')
